[package]
name = "oxygen"
version = "0.1.0"
edition = "2021"

[dependencies]
oxygen_error = { path = "../oxygen_error" }
oxygen_options = { path = "../oxygen_options" }
oxygen_parser = { path = "../oxygen_parser" }
